packages:
  - "packages/**"
  - "internal/*"

catalog:
  turbo: ^2.7.3
  prettier: ^3.7.4
  typescript: ^5.9.3
  vite-enhance: ^0.3.2
  '@changesets/cli': ^2.29.8
  '@iconify/json': ^2.2.406
  '@iconify/tailwind': ^1.2.0
  '@iconify/vue': ^5.0.0
  '@manypkg/get-packages': ^3.1.0
  '@tailwindcss/nesting': ^0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.19
  'lucide-vue-next': ^0.562.0
  vue: ^3.5.26
  'vue-router': ^4.6.4
  'vue-tsc': ^3.2.1
  unbuild: ^3.6.1
  autoprefixer: ^10.4.21
  '@ctrl/tinycolor': ^4.2.0
  '@tanstack/vue-store': ^0.8.0
  '@vue/shared': ^3.5.26
  '@vueuse/core': ^14.1.0
  'class-variance-authority': ^0.7.1
  clsx: ^2.1.1
  cssnano: ^7.1.2
  dayjs: ^1.11.19
  defu: ^6.1.4
  'es-toolkit': ^1.43.0
  jiti: ^2.6.1
  'lodash.clonedeep': ^4.5.0
  nprogress: ^0.2.0
  postcss: ^8.5.6
  'postcss-antd-fixes': ^0.2.0
  'postcss-import': ^16.1.1
  'postcss-preset-env': ^10.6.0
  'reka-ui': ^2.7.0
  sass: ^1.97.1
  sortablejs: ^1.15.6
  tailwindcss: ^4.1.18
  'tailwindcss-animate': ^1.0.7
  'tailwind-merge': ^3.4.0
  'theme-colors': ^0.1.0
  'vee-validate': ^4.15.1
  '@vee-validate/zod': ^4.15.1
  zod: ^4.2.1
  'zod-defaults': ^0.2.3
  '@types/lodash.clonedeep': ^4.5.9
  '@types/lodash.get': ^4.4.9
  '@types/lodash.isequal': ^4.5.8
  '@types/lodash.set': ^4.3.9
  '@types/node': ^25.0.3
  '@types/nprogress': ^0.2.3
  '@types/postcss-import': ^14.0.3
  '@types/sortablejs': ^1.15.9