packages:
  - "packages/*"
  - "internal/*"

catalog:
  turbo: ^2.7.3
  prettier: ^3.7.4
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  unbuild: ^3.6.1
  tsup: ^8.5.0
  sass: ^1.97.1
  vue: ^3.5.26
  tailwindcss: ^4.1.18
  "@vitejs/plugin-vue": ^6.0.3
  "@changesets/cli": ^2.29.8
  "@iconify/json": ^2.2.425
  "@iconify/tailwind": ^1.2.0
  "@iconify/vue": ^5.0.0
  "@vueuse/core": ^14.1.0